export const options = [
  { title: "react" },
  { title: "reactjs" },
  { title: "python" },
  { title: "flask" },
  { title: "golang" },
  { title: "go" },
  { title: "c" },
  { title: "c++" },
  { title: "c#" },
  { title: "fortran" },
  { title: "clojure" },
  { title: "swift" },
  { title: "objective-c" },
  { title: "vue" },
  { title: "vuejs" },
  { title: "angular" },
  { title: "angularjs" },
];
